In [1]:
import pandas as pd
df_inf = pd.read_csv("dataframe_influencers.csv")

In [2]:
df_inf.info()

<class 'pandas.DataFrame'>
RangeIndex: 33935 entries, 0 to 33934
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Username   33935 non-null  str
 1   Category   33935 non-null  str
 2   Followers  33935 non-null  int64
 3   Followees  33935 non-null  int64
 4   Posts      33935 non-null  int64
dtypes: int64(3), str(2)
memory usage: 1.9 MB

In [3]:
df_inf.describe()

          Followers      Followees          Posts
count  3.393500e+04   33935.000000   33935.000000
mean   1.403299e+05    1531.588242    1487.183409
std    1.245163e+06    2274.896034    2187.174919
min    1.000000e+03       0.000000     100.000000
25%    4.951500e+03     557.000000     538.000000
50%    1.612500e+04     974.000000     937.000000
75%    5.356550e+04    1828.000000    1732.000000
max    9.647601e+07  304758.000000  127520.000000

In [4]:
df_inf.head()

            Username Category  Followers  Followees  Posts
0        makeupbynvs   beauty       1432       1089    363
1  jaquelinevandoski   beauty     137600        548    569
2      anisaartistry   beauty      64644        289    391
3  rubina_muartistry   beauty     496406        742    887
4        beautyxabbi   beauty       2050       1423    751

In [5]:
len(df_inf)

33935

In [6]:
df_inf["Category"].unique()

<ArrowStringArray>
[  'beauty',   'family',  'fashion',  'fitness',     'food', 'interior',
      'pet',   'travel',    'other']
Length: 9, dtype: str

In [7]:
df_inf.groupby("Category")["Followers"].agg(["count","median","max"]).round(4)

          count   median       max
Category
beauty     1542  18249.0  13957201
family     4070  11188.0  80465206
fashion   11913  23564.0  96476007
fitness    1133  28290.0  28834289
food       3565  12554.0   2730067
interior   1195  19957.0   1703450
other      5720   8718.0  80852821
pet         587  20755.0   4284911
travel     4210  13133.0   9154933

In [8]:
df_inf.loc[df_inf["Username"] == "vanessachristinne"]

Empty DataFrame
Columns: [Username, Category, Followers, Followees, Posts]
Index: []

In [11]:
df_inf.loc[df_inf["Username"] == "drienne48"]

Empty DataFrame
Columns: [Username, Category, Followers, Followees, Posts]
Index: []